### ISSUE TITLE
Won't display on IP report if Port has no name defined

### ISSUE THREAD

**Issue by jasonheffner** [pluginsGLPI/addressing#13]
If a device or computer has a network port with no name defined, or just a "0", it won't show up on the report list. Adding a name or changing it from something other than "0" then displays on the listing. Possible data type problem?

**Comment by hawkguild** [comment]
Jsjs

**Comment by jasonheffner** [comment]
Actually, this appears to have been fixed by a newer version since my report here. I believe this could actually be closed.
