### ISSUE TITLE
[GLPI 0.85 & 0.90.5] Plugin not detected

### ISSUE THREAD

**Issue by ravier2000** [pluginsGLPI/addressing#16]
Hello,

I tried to install the IP Report plugin on my GLPI / FI server, but unsuccessfully.
I downloaded the proper version from github, unzipped it onto /var/..../glpi/plugins but the plugin does not appear in Configuration/Plugins on the GLPI web interface. 
I tried with GLPI 0.85 and GLPI 0.90.5, same result.
This is very strange as I already have plugins enabled on GLPI.

Is this bug known ? If so, is there a way to solve this issue ?

**Comment by amma35** [comment]
Hi,

What is the plugin folder name in glpi/plugins/?

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
