### ISSUE TITLE
search in IP adressing

### ISSUE THREAD

**Issue by AliouneDiop** [pluginsGLPI/addressing#19]
Dear
When I search for example all items with the ip address starting with 172,I just received one result despite  I changed the search criteria. What is the best way to have in the results all IP starting with 172 for example.
Thanks
![ip](https://user-images.githubusercontent.com/29062043/30198106-3d0afd4e-946c-11e7-8d6a-ca30ffc1171e.JPG)

**Comment by amma35** [comment]
Hi,
It isn't currently possible to search on the IP address.
