### ISSUE TITLE
Doesn`t work with glpi 9.1

### ISSUE THREAD

**Issue by insolito-pt** [pluginsGLPI/addressing#2]
It is my first time here hope I`m note posting in the wrong place, but it does not work with glpi 9.1, I tried to install like I install several times like I install the other pluggins  and nothing.

thank you

**Comment by amma35** [comment]
The plugin is not compatible for GLPI Version 9.1 currently.

Where did you download the plugin, the release or the master?

**Comment by insolito-pt** [comment]
Thank for the really fast reply, like I told you I`m new here, I downloaded from here:
https://github.com/pluginsGLPI/addressing/releases
 Version 2.3.0 released for GLPI >= 0.90 and < 0.91
Source code (tar.gz)  
and only now I saw this " >= 0.90 and < 0.91 "  :)
Hope you realease soon for 9.1
Sorry and thank you
