### ISSUE TITLE
Update plugin for glpi 9.2

### ISSUE THREAD

**Issue by jsamaniegog** [pluginsGLPI/addressing#20]
Update plugin for glpi 9.2

Thank you very much.

**Comment by C-Duv** [comment]
Do you need any help for updating the plugin?

**Comment by jsamaniegog** [comment]
Hi @C-Duv ,
Version 2.5.0 is for GLPI >= 9.1.1 and < 9.2, the plugin must be updated to work with GLPI 9.2.

Thank you.

**Comment by ciadch** [comment]
Do you have any idea when plugin will be compatible with 9.2 ? It is really usefull :-)

Thanks four the job !

**Comment by amma35** [comment]
see https://github.com/pluginsGLPI/addressing/releases/tag/2.6.0

**Comment by ciadch** [comment]
Thanks !
