### ISSUE TITLE
IP field empty and computer not showing

### ISSUE THREAD

**Issue by supports2l** [pluginsGLPI/addressing#25]
Hello,

I'm using _GLPI 9.2.1_ with the plugin _Addressing 2.6.0_.
Before I upgraded from 9.1.6 with plugin 2.5.0, everything worked well.

Now, when I generate my reports, the column IP is empty. When I switch on the debug mode, I can see this PHP Warning:

![image](https://user-images.githubusercontent.com/37071972/36975723-54cc2bd8-207b-11e8-8912-97bbc074f23d.png)

I've tested to add a Network on my computers 
![image](https://user-images.githubusercontent.com/37071972/36975028-0dc3048e-2079-11e8-865e-ea5dd7a950b2.png)
The two computers (S2LApp2, S2LApp3) which have the Network filled are displayed, but without IP.
The other computer which have no Network are not displayed at all.

When I try to generate a report for an other ip range, with Devices and not Computer, the same error occurs:
![image](https://user-images.githubusercontent.com/37071972/36976025-5d4a9816-207c-11e8-8606-aa8022440cc8.png)

**Comment by amma35** [comment]
Hi,

Did you change PHP version between the two updates?

**Comment by supports2l** [comment]
Hi,
no changes on the web server.
I'm using PHP 7.1.6
![image](https://user-images.githubusercontent.com/37071972/36981977-d9fc232c-208e-11e8-99e6-931a3e89e927.png)

**Comment by amma35** [comment]
Can we debug together? 
I can't reproduce your mistake.

**Comment by supports2l** [comment]
Yes gladly,

I can provide you an access to my GLPI.
How do you want to proceed ?

**Comment by amma35** [comment]
With internet searches, there seems to be a problem with 32-bit architectures: https://bugs.php.net/bug.php?id=74417&edit=1

Make a copy of the file before applying the changes.

We'd have to postpone his modifications for testing: 

```--- a/inc/report.class.php
+++ b/inc/report.class.php
@@ -126,7 +126,7 @@ class PluginAddressingReport extends CommonDBTM {
       $user = new User();
 
       foreach ($result as $num => $lines) {
-         $ip = long2ip(substr($num, 2));
+         $ip = self::string2ip(substr($num, 2));
 
          if (count($lines)) {
             if (count($lines) > 1) {
@@ -276,6 +276,13 @@ class PluginAddressingReport extends CommonDBTM {
       return $ping_response;
    }
 
+   function string2ip($s) {
+      //TODO TEST
+      Toolbox::logDebug(PHP_INT_MAX);
+      if ($s > PHP_INT_MAX)
+         $s = 2 * PHP_INT_MIN + $s;
+      return long2ip($s);
+   }
```

Replace the line `$ip = long2ip (substr ($num, 2));` with `$ip = self:: string2ip (substr ($num, 2)); ` and add the function `string2ip($s)`

Can you give me the php-errors. log file again by going to the front interface?

**Comment by supports2l** [comment]
The IP's are now displayed ! Thanks a lot !

![image](https://user-images.githubusercontent.com/37071972/37029599-581ba918-2138-11e8-9569-21f0a0e00c62.png)

And I have understood why only my computers with a Network specified were displayed. 
I selected a network when I edited my _IP Adressing item_. So only the computers with this network were displayed. Now everything is functionnal !

![image](https://user-images.githubusercontent.com/37071972/37030182-45a3084c-213a-11e8-9643-570b40918b7e.png)

Thanks

**Comment by supports2l** [comment]
And here is the log
[php-errors.log](https://github.com/pluginsGLPI/addressing/files/1784917/php-errors.log)

**Comment by amma35** [comment]
Ok thank you.

The instances with 32-bit architectures have a very small PHP variable which is why the IP addresses didn't pass.

I would release a new release but in the meantime you can keep this fix, you'd just have to remove the line `Toolbox::logDebug(PHP_INT_MAX);`  shortly after `//TODO TEST`
