### ISSUE TITLE
Ping IP unable to detect the proper system

### ISSUE THREAD

**Issue by jlucgauthier** [pluginsGLPI/addressing#27]
Hello,
GLPI 9.2.1 is hosted in IIS on Windows Server 2008 R2. If we try to ping equipment, it shows an error message related to the **-c parameter** that is not supported. Well, on Windows systems it true.

Has a work around I switch Case 0 and Case 1 from ping_equipment.class.php. So it's working now, but I'just want to make sure that it won't affect anything else - I guess not ?!

function ping($system, $ip) {
      $error = 1;
      $list  ='';
      switch ($system) {
        case 0 :
            _//windows
            exec("ping.exe -n 1 -w 1 -i 4 ".$ip, $list, $error);_
            break;
	case 1 :
            _// linux ping
            exec("ping -c 1 -w 1 ".$ip, $list, $error);_
            break;

**Comment by amma35** [comment]
Hi,
The system is selected in the plugin setup: 
![config](https://user-images.githubusercontent.com/15138371/44339944-90b12680-a483-11e8-957b-74dd6d7002c2.png)
