### ISSUE TITLE
Computers IP address couldn't link to addressing

### ISSUE THREAD

**Issue by hqm8512** [pluginsGLPI/addressing#29]
I have added a item in assets->computers , but i couldn't find it in addressing

**Comment by amma35** [comment]
It would be necessary to us to detail the various elements which you put in place: 

1. IP addressing that you have configured: 
![2018-08-20 13_40_42-glpi - adressage ip - 2](https://user-images.githubusercontent.com/15138371/44338720-21393800-a47f-11e8-9da9-405d7d3cf115.png)
2. How is configured your PC / Network Port

**Comment by jcervantes-sipecom** [comment]
Hi, I cannot too and as I said in #37 I attached images:

![Screenshot_16](https://user-images.githubusercontent.com/56606032/85461578-216a5900-b56a-11ea-84ea-c078f03fb3c9.png)

![Screenshot_17](https://user-images.githubusercontent.com/56606032/85461583-229b8600-b56a-11ea-9c4e-dec5d9698b17.png)

![Screenshot_18](https://user-images.githubusercontent.com/56606032/85462861-9722f480-b56b-11ea-9a67-8955098e0844.png)

![Screenshot_19](https://user-images.githubusercontent.com/56606032/85463327-216b5880-b56c-11ea-96bc-33d4d1db4390.png)

![Screenshot_20](https://user-images.githubusercontent.com/56606032/85463332-229c8580-b56c-11ea-823b-c684a5fb81a8.png)

**Comment by jcervantes-sipecom** [comment]
I solved deselecting the "Select the network" as I said in #37
