### ISSUE TITLE
Testing on GLPI 9.1

### ISSUE THREAD

**Issue by gitdevmod** [pluginsGLPI/addressing#3]
Hi,
How to install addressing plugin with GLPI 9.1 ? or maybe better to wait new release ?
Thanks in advance

**Comment by tsmr** [comment]
The plugin is not compatible at this time (please wait)

**Comment by gitdevmod** [comment]
Ok, I'll wait, thx @tsmr

**Comment by kaiser2mars** [comment]
Bonjour, j'utilise depuis tres longtemps maintenant ce plugin pour ma gestion des VLAN, j ai fais evolué en 9.1 GLPI avant de verifier sa compatibilité ...
@tsmr Avez vous une idee du temps de développement ?
Merci d'avance pour votre travail.
