### ISSUE TITLE
Will this be available for GLPI version 9.3 soon?

### ISSUE THREAD

**Issue by Albager** [pluginsGLPI/addressing#31]
We are setting up GLPI for the first time and are running the latest version. Will the IP addressing plugin be available for GLPI version 9.3 soon?

**Comment by fcrispim77** [comment]
We need too

**Comment by yanok45** [comment]
We too. thank you

**Comment by Basicek1** [comment]
We too. Thank you ;-)

**Comment by dougti** [comment]
+1

**Comment by amma35** [comment]
see https://github.com/pluginsGLPI/addressing/releases/tag/2.7.0
