### ISSUE TITLE
GLPI 9.4.1.1 fping

### ISSUE THREAD

**Issue by zoriax** [pluginsGLPI/addressing#36]
Hello,

I'm not sure it's a bug but since GLPI 9.4.1.1 I can't use fping anymore. After a few search, I must enter fullpath to exec command : 
```php
exec("/usr/sbin/fping -r1 -c1 -t100 ".$ip, $list);
```
And I have this message at the end of report

![image](https://user-images.githubusercontent.com/12936546/55083191-640d5f00-50a3-11e9-80a8-b8a53657a183.png)

Without that, it dosen't work.

Any idea / workaround ? 

Thanks for you help !

**Comment by tsmr** [comment]
Obsolete issue, i close
