### ISSUE TITLE
IP addresses associated with an ethernet port

### ISSUE THREAD

**Issue by aanriot** [pluginsGLPI/addressing#37]
Hello,

I have a network equipment on which I added several IP addresses on its ethernet port. But they are not displayed as used (or reserved) on the IP report.

Is there a trick to achieve this?

Thanks a lot.

**Comment by jcervantes-sipecom** [comment]
Hi, I got the same problem, and I want to know how to resolve it. I attached examples.

![Screenshot_16](https://user-images.githubusercontent.com/56606032/85445954-8bc6cd80-b559-11ea-8d1b-7c0f4a9e2fa4.png)
![Screenshot_17](https://user-images.githubusercontent.com/56606032/85445961-8d909100-b559-11ea-8b21-35b9f0b9e55f.png)

**Comment by jcervantes-sipecom** [comment]
I find the problem, in the IP Addresing option I have selected the network:

![image](https://user-images.githubusercontent.com/56606032/90076597-c5989280-dcc5-11ea-9371-2745336f915e.png)

After I deselected the plugins works:
![image](https://user-images.githubusercontent.com/56606032/90076708-0ee8e200-dcc6-11ea-8097-87d75a52e6cc.png)

And shows the computers on the report option inside IP Addresing option.
