### ISSUE TITLE
Class 'Event' not found

### ISSUE THREAD

**Issue by aanriot** [pluginsGLPI/addressing#38]
Hello,

I get the following message while trying to reserve an IP address:

```
PHP Fatal error:  Uncaught Error: Class 'Event' not found in /var/www/glpi-9.4.3/plugins/addressing/inc/reserveip.class.php:125\nStack trace:\n#0 /var/www/glpi-9.4.3/plugins/addressing/front/reserveip.form.php(36): PluginAddressingReserveip->reserveip(Array)\n#1 {main}\n  thrown in /var/www/glpi-9.4.3/plugins/addressing/inc/reserveip.class.php on line 125, referer: http://fqdn/plugins/addressing/front/addressing.form.php?id=5
```
Furthemore, even when commenting out these lines, the reservation doesn't work.

We are using GLPI 9.4.3.

Thanks a lot.

**Comment by Casim0d0** [comment]
I have the same issue. After a reload the new device is shown as a new ressource for the reserved ip.

**Comment by sslevil** [comment]
Any news on this issue?

`Fatal error: Uncaught Error: Class 'Event' not found in /srv/http/apache2/vhosts/xxxxxxx/www/plugins/addressing/inc/reserveip.class.php:125 Stack trace: #0 /srv/http/apache2/vhosts/xxxxxxx/www/plugins/addressing/front/reserveip.form.php(36): PluginAddressingReserveip->reserveip(Array) #1 {main} thrown in /srv/http/apache2/vhosts/xxxxxxx/www/plugins/addressing/inc/reserveip.class.php on line 125 `

**Comment by deja001** [comment]
Have the same issue : 
Fatal error: Uncaught Error: Class 'Event' not found in /var/www/html/glpi_test/plugins/addressing/inc/reserveip.class.php:125 Stack trace: #0 /var/www/html/glpi_test/plugins/addressing/front/reserveip.form.php(36): PluginAddressingReserveip->reserveip(Array) #1 {main} thrown in /var/www/html/glpi_test/plugins/addressing/inc/reserveip.class.php on line 125

The problem occurs with Chrome, but unable to reproduce the bug  with IE11

**Comment by Kaya84** [comment]
Open /glpi/plugins/simcard/front/simcard.form.php and insert
use Glpi\Event;
before 
include ('../../../inc/includes.php');

**Comment by deja001** [comment]
Thank you, it works !
