### ISSUE TITLE
Crashed using glpi 9.4.5

### ISSUE THREAD

**Issue by teguh-umar** [pluginsGLPI/addressing#43]
have some problem wity IP addressing plugins, after instal it, configure it, the plugins is crashed and now it has broom icon

did i miss something?

GLPI 9.4.5
Installation mode: RPM
IP Adressing     addressing     2.8.0
![image](https://user-images.githubusercontent.com/62581388/77476261-d6e31e80-6e4c-11ea-994d-2172f664513a.png)

**Comment by tsmr** [comment]
Obsolete issue, i close
