### ISSUE TITLE
9.1 support

### ISSUE THREAD

**Issue by Stoatwblr** [pluginsGLPI/addressing#5]
This plugin needs a release update for 9.1

**Comment by hdep** [comment]
Hello,
I did try to install this plugin on GLPI 9.1
But the plugin doesn't show up in plugin list. Is this the same issue ?

**Comment by orthagh** [comment]
@tsmr, the xml of this plugin (and [plugins directory](http://plugins.glpi-project.org/#/plugin/addressing)) mentions a 2.4.0 version compatible 9.1 but inexistent on github.

Is this a miss ?

**Comment by tsmr** [comment]
Yes i think. We waiting for 9.1.1 release for release plugin

**Comment by kaiser2mars** [comment]
ok thank, so wait and see

**Comment by Armin83** [comment]
Again there http://plugins.glpi-project.org/#/ is mentioned a 2.4.0 release but i don't see this on github.

**Comment by orthagh** [comment]
9.1.1 released :)

**Comment by mcjarod** [comment]
Yes there http://plugins.glpi-project.org/#/ is mentioned a 2.4.0 release but i don't see this on github.

**Comment by amma35** [comment]
Release create : https://github.com/pluginsGLPI/addressing/releases/tag/2.5.0
