### ISSUE TITLE
[2.9.1] Include error

### ISSUE THREAD

**Issue by cyrakuse** [pluginsGLPI/addressing#54]
I have many PHP errors like this : 
glpiphplog.WARNING:   *** PHP Warning (2): include(): Failed opening '/glpi/plugins/addressing/ajax/seePingTab.php' for inclusion ....

And the "Save" button disapear in the computers form.

I installed this plugin from the marketplace.

The problem is in the pinginfo.class.php file : 
- line 215, there is : 
$CFG_GLPI["root_doc"] . "/plugins/addressing/ajax/seePingTab.php",
I replace this line by : 
$CFG_GLPI["root_doc"] . "/marketplace/addressing/ajax/seePingTab.php",

The same with the line 224, there is : 
include(GLPI_ROOT . "/plugins/addressing/ajax/seePingTab.php");
i replace this line qith : 
include(GLPI_ROOT . "/marketplace/addressing/ajax/seePingTab.php");

**Comment by cyrakuse** [comment]
Another place with wrong url : in the file ping_equipment.class.php line 119

Replace : 
$('#ping_response').load('" . $CFG_GLPI["root_doc"] . "/plugins/addressing/ajax/ping.php', {

By : 
$('#ping_response').load('" . $CFG_GLPI["root_doc"] . "/marketplace/addressing/ajax/ping.php', {

**Comment by tsmr** [comment]
Already corrected
