### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by kaiser2mars** [pluginsGLPI/addressing#6]
Bonjour, apres avoir fait la mise a jour en version 9.1.1 et le nouveau plugin , j'ai des erreurs http500...
Je vois bien ces traces d'erreurs mais je ne sais pas quoi faire...
Pouvez vous m'aider?
merci
[Thu Nov 24 09:22:31.126375 2016] [:error] [pid 1937] [client Y.Y.Y.Y:56524] PHP Fatal error:  Uncaught exception 'Zend\\I18n\\Exception\\InvalidArgumentException' with message 'Could not find or open file /var/www/glpi/plugins/addressing/locales/ for reading' in /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php:49\nStack trace:\n#0 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(700): Zend\\I18n\\Translator\\Loader\\Gettext->load('language', '/var/www/glpi/p...')\n#1 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(572): Zend\\I18n\\Translator\\Translator->loadMessagesFromFiles('addressing', 'language')\n#2 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(440): Zend\\I18n\\Translator\\Translator->loadMessages('addressing', 'language')\n#3 /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(388): Zend\\I18n\\Translator\\Translator->getTranslatedMessage('IP Adressing', 'language', 'addressing')\n#4 /var/www/glpi/inc/autoload.function.php(171): Zend\\I18n\\Translator\\Translator->translatePlural('IP  in /var/www/glpi/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php on line 49, referer: https://X.X.X.X/

**Comment by amma35** [comment]
Version 9.1.1 was not output.
The master you took was under development.

Do you still have the same error with the release: https://github.com/pluginsGLPI/addressing/releases/tag/2.5.0

**Comment by amma35** [comment]
I'm closing for now, feel free to reopen if issue persists.
