### ISSUE TITLE
Export report not working

### ISSUE THREAD

**Issue by Fbutty** [pluginsGLPI/addressing#70]
Good morning,
We are under GLPI 10.0.6 and we use the addressing plugin in version 3.0.1. This plugin is very useful to us and it works great.
We have a small problem with exports.
When we export a report to CSV, it will be exported but the data inside is lines of codes. [exemple.csv](https://github.com/pluginsGLPI/addressing/files/11049733/glpi.1.csv)
When we export to PDF, a blank page appears and nothing happens.
Do you have a solution ?
Thank you for your help.
Franck

**Comment by reiters-it** [comment]
same problem on my side with GLPI 10.0.7 and plugin 3.0.1.

output in google chrome and also in firefox
![image](https://github.com/pluginsGLPI/addressing/assets/99324507/2002db7e-c67d-4a1d-8b0b-677262998af8)

**Comment by Fbutty** [comment]
UP ?

**Comment by berilslv** [comment]
Can we wait for this fix? Facing same issue 10.0.10
Thanks!

**Comment by cairoapcampos** [comment]
I have the same problem.

**Comment by tsmr** [comment]
Fixed in next version
