### ISSUE TITLE
PHP Warnung 

### ISSUE THREAD

**Issue by NeueMedienBecker** [pluginsGLPI/addressing#73]
Hello,

I have the following PHP error after switching to 10.09, is there a solution?

[2023-09-13 18:43:38] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared for "glpi_ticketcategories" table. Table does not correspond to a known itemtype. in /home/users/glpi/www/src/DbUtils.php at line 2064
  Backtrace :
  src/DbUtils.php:2064                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/CommonDBTM.php:4627                            CommonDBTM->delete()
  marketplace/addressing/inc/pinginfo.class.php:106  CommonDBTM->deleteByCriteria()
  marketplace/addressing/inc/pinginfo.class.php:88   PluginAddressingPinginfo->updateAnAddressing()
  marketplace/addressing/inc/pinginfo.class.php:70   PluginAddressingPinginfo->updateAllAddressing()
  src/CronTask.php:1018                              PluginAddressingPinginfo::cronUpdatePing()
  front/cron.php:83                                  CronTask::launch()

[2023-09-13 18:43:38] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_documents" and "glpi_plugin_manageentities_companies" table. Target field "logo_id" is not a foreign key field. in /home/users/glpi/ww>
  Backtrace :
  src/DbUtils.php:2176                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/CommonDBTM.php:4627                            CommonDBTM->delete()
  marketplace/addressing/inc/pinginfo.class.php:106  CommonDBTM->deleteByCriteria()
  marketplace/addressing/inc/pinginfo.class.php:88   PluginAddressingPinginfo->updateAnAddressing()
  marketplace/addressing/inc/pinginfo.class.php:70   PluginAddressingPinginfo->updateAllAddressing()
  src/CronTask.php:1018                              PluginAddressingPinginfo::cronUpdatePing()
  front/cron.php:83                                  CronTask::launch()

[2023-09-13 18:43:38] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared between "glpi_printers" and "glpi_plugin_printercounters_items_billingmodels" table. Target field "items_id" is not a foreign key field. in /home/us>
  Backtrace :
  src/DbUtils.php:2176                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/CommonDBTM.php:4627                            CommonDBTM->delete()
  marketplace/addressing/inc/pinginfo.class.php:106  CommonDBTM->deleteByCriteria()
  marketplace/addressing/inc/pinginfo.class.php:88   PluginAddressingPinginfo->updateAnAddressing()
  marketplace/addressing/inc/pinginfo.class.php:70   PluginAddressingPinginfo->updateAllAddressing()
  src/CronTask.php:1018                              PluginAddressingPinginfo::cronUpdatePing()
  front/cron.php:83                                  CronTask::launch()

**Comment by MasinAD** [comment]
I get this warning, too:
```
PHP User Warning (512): Invalid relations declared for "glpi_ticketcategories" table. Table does not correspond to a known itemtype. in /srv/http/glpi/src/DbUtils.php at line 2059
```
when I sync the LDAP users:
```
sudo -u www-data /srv/http/glpi/bin/console ldap:sync -n
```
The warning does not appear for every user, though. It appears 12 times for a sync of 187 users.

**Comment by tsmr** [comment]
No related to this plugin. I close
