### ISSUE TITLE
IP Reserve

### ISSUE THREAD

**Issue by raiched** [pluginsGLPI/addressing#8]
Great plugin - I'm still having trouble setting up the IP reservation. There is a "reserve" designator but it doesn't really seem to set anything in the database with a 'reserved' flag. Running GLPI 9.1.1 - fusioninventory and assists are being queried correctly and show in the IP report. 
"If in GLPI, you declare the name of a port of equipment (except network hardware) with the string “reserve” within its name, the IP will appear in the plugin as reserved."

So to be clear, I need to create phantom ports someplace and then add 'reserve' to the port name?
If this isn't the correct place for functional questions please direct.  Thank you

**Comment by MarcinJanowski** [comment]
I have this same problem.

**Comment by amma35** [comment]
The name when adding the networkport with the addressing plugin is formatted as "reserv-{ip}".
When the report is displayed, networkports starting with "reserv" are therefore considered as reserved.
